// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEDKE2PVGOvhD4T0M3DfvnJtu0nhbEqHU',
    appId: '1:110108161864:web:0bfd3032d6a9bde7f0257d',
    messagingSenderId: '110108161864',
    projectId: 'scout-app-a711f',
    authDomain: 'scout-app-a711f.firebaseapp.com',
    storageBucket: 'scout-app-a711f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNKMLXtRYV2n_vDOsSK6dZxbFpSSSL1k',
    appId: '1:110108161864:android:bfc8eb682b39bd89f0257d',
    messagingSenderId: '110108161864',
    projectId: 'scout-app-a711f',
    storageBucket: 'scout-app-a711f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVm5dECROvJQZgGLTazNX5xskwBnyIjH8',
    appId: '1:110108161864:ios:6fe8f4b3997288daf0257d',
    messagingSenderId: '110108161864',
    projectId: 'scout-app-a711f',
    storageBucket: 'scout-app-a711f.appspot.com',
    iosBundleId: 'com.example.scoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVm5dECROvJQZgGLTazNX5xskwBnyIjH8',
    appId: '1:110108161864:ios:6fe8f4b3997288daf0257d',
    messagingSenderId: '110108161864',
    projectId: 'scout-app-a711f',
    storageBucket: 'scout-app-a711f.appspot.com',
    iosBundleId: 'com.example.scoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEDKE2PVGOvhD4T0M3DfvnJtu0nhbEqHU',
    appId: '1:110108161864:web:0721888e38c2634af0257d',
    messagingSenderId: '110108161864',
    projectId: 'scout-app-a711f',
    authDomain: 'scout-app-a711f.firebaseapp.com',
    storageBucket: 'scout-app-a711f.appspot.com',
  );
}
